CREATE TABLE TCI_ATENDIMENTO (
    ID              INTEGER NOT NULL,
    SEGUNDA         VARCHAR2(35),
    TERCA           VARCHAR2(35),
    QUARTA          VARCHAR2(35),
    QUINTA          VARCHAR2(35),
    SEXTA           VARCHAR2(35),
    SABADO          VARCHAR2(35),
    DOMINGO         VARCHAR2(35),
    FERIADO         VARCHAR2(35),
    TCI_EMPRESA_ID  INTEGER NOT NULL
);

CREATE UNIQUE INDEX TCI_ATENDIMENTO__IDX ON
    TCI_ATENDIMENTO (
        TCI_EMPRESA_ID
    ASC );

ALTER TABLE TCI_ATENDIMENTO ADD CONSTRAINT TCI_ATENDIMENTO_PK PRIMARY KEY ( ID,
                                                                            TCI_EMPRESA_ID );

CREATE TABLE TCI_CATEGORIA (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR2(50)
);

ALTER TABLE TCI_CATEGORIA ADD CONSTRAINT TCI_CATEGORIA_PK PRIMARY KEY ( ID );

CREATE TABLE TCI_EMPRESA (
    ID                  INTEGER NOT NULL,
    NOME                VARCHAR2(255) NOT NULL,
    DESCRICAO           VARCHAR2(1000) NOT NULL,
    CRIADOEM            DATE NOT NULL,
    PEDIDOMIN           NUMBER(6, 2) NOT NULL,
    LOGO                BLOB,
    INFO                VARCHAR2(1000),
    CNPJ                VARCHAR2(18) NOT NULL,
    RAZAOSOCIAL         VARCHAR2(250) NOT NULL,
    TELEFONE            VARCHAR2(9) NOT NULL,
    POSSUIENTREGA       CHAR(1) NOT NULL,
    TCI_PLANO_ID        INTEGER NOT NULL
    TCI_RESPONSAVEL_ID  INTEGER NOT NULL
);

ALTER TABLE TCI_EMPRESA ADD CONSTRAINT TCI_EMPRESA_PK PRIMARY KEY ( ID );

CREATE TABLE TCI_EMPRESACAT (
    TCI_EMPRESA_ID    INTEGER NOT NULL,
    TCI_CATEGORIA_ID  INTEGER NOT NULL,
    NOME              VARCHAR2(50)
);

ALTER TABLE TCI_EMPRESACAT ADD CONSTRAINT TCI_EMPRESACAT_PK PRIMARY KEY ( TCI_EMPRESA_ID,
                                                                          TCI_CATEGORIA_ID );

CREATE TABLE TCI_ENDERECO (
    ID              INTEGER NOT NULL,
    LOGRADOURO      VARCHAR2(255) NOT NULL,
    NUMERO          INTEGER NOT NULL,
    CIDADE          VARCHAR2(50) NOT NULL,
    UF              CHAR(2) NOT NULL,
    CEP             VARCHAR2(10) NOT NULL,
    PAIS            VARCHAR2(255),
    TCI_EMPRESA_ID  INTEGER NOT NULL
);

CREATE UNIQUE INDEX TCI_ENDERECO__IDX ON
    TCI_ENDERECO (
        TCI_EMPRESA_ID
    ASC );

ALTER TABLE TCI_ENDERECO ADD CONSTRAINT TCI_ENDERECO_PK PRIMARY KEY ( ID,
                                                                      TCI_EMPRESA_ID );

CREATE TABLE TCI_ITEM (
    ID                 INTEGER NOT NULL,
    NOME               VARCHAR2(50) NOT NULL,
    DESCRICAO          VARCHAR2(1000) NOT NULL,
    PRECO              NUMBER(6, 2) NOT NULL,
    CRIADOEM           DATE NOT NULL,
    FOTO               BLOB,
    TCI_CARDAPIO_ID  INTEGER NOT NULL
);

ALTER TABLE TCI_ITEM ADD CONSTRAINT TCI_ITEM_PK PRIMARY KEY ( ID );

CREATE TABLE TCI_PLANO (
    ID     INTEGER NOT NULL,
    NOME   VARCHAR2(50) NOT NULL,
    PRECO  NUMBER(6, 2) NOT NULL
);

ALTER TABLE TCI_PLANO ADD CONSTRAINT TCI_PLANO_PK PRIMARY KEY ( ID );

CREATE TABLE TCI_CARDAPIO (
    ID              INTEGER NOT NULL,
    TITULO          VARCHAR2(50) NOT NULL,
    DESTAQUE        CHAR(1) NOT NULL,
    CRIADOEM        DATE NOT NULL,
    TCI_EMPRESA_ID  INTEGER NOT NULL
);

ALTER TABLE TCI_CARDAPIO ADD CONSTRAINT TCI_CARDAPIO_PK PRIMARY KEY ( ID );

CREATE TABLE TCI_RESPONSAVEL (
    ID         INTEGER NOT NULL,
    EMAIL      VARCHAR2(100) NOT NULL,
    NOME       VARCHAR2(100) NOT NULL,
    SOBRENOME  VARCHAR2(100) NOT NULL,
    CPF        VARCHAR2(15) NOT NULL,
    RG         VARCHAR2(15) NOT NULL,
    UF         CHAR(2) NOT NULL,
    TERMOS     CHAR(1) NOT NULL
);

ALTER TABLE TCI_RESPONSAVEL ADD CONSTRAINT TCI_RESPONSAVEL_PK PRIMARY KEY ( ID );

ALTER TABLE TCI_ATENDIMENTO
    ADD CONSTRAINT TCI_ATENDIMENTO_TCI_EMPRESA_FK FOREIGN KEY ( TCI_EMPRESA_ID )
        REFERENCES TCI_EMPRESA ( ID )
            ON DELETE CASCADE;

ALTER TABLE TCI_EMPRESA
    ADD CONSTRAINT TCI_EMPRESA_TCI_PLANO_FK FOREIGN KEY ( TCI_PLANO_ID )
        REFERENCES TCI_PLANO ( ID );

ALTER TABLE TCI_EMPRESA
    ADD CONSTRAINT TCI_EMPRESA_TCI_RESPONSAVEL_FK FOREIGN KEY ( TCI_RESPONSAVEL_ID )
        REFERENCES TCI_RESPONSAVEL ( ID )
            ON DELETE CASCADE;

ALTER TABLE TCI_EMPRESACAT
    ADD CONSTRAINT TCI_EMPRESAcat_TCI_CATEGOR_FK FOREIGN KEY ( TCI_CATEGORIA_ID )
        REFERENCES TCI_CATEGORIA ( ID );

ALTER TABLE TCI_EMPRESACAT
    ADD CONSTRAINT TCI_EMPRESAcat_TCI_EMPRESA_FK FOREIGN KEY ( TCI_EMPRESA_ID )
        REFERENCES TCI_EMPRESA ( ID );

ALTER TABLE TCI_ENDERECO
    ADD CONSTRAINT TCI_ENDERECO_TCI_EMPRESA_FK FOREIGN KEY ( TCI_EMPRESA_ID )
        REFERENCES TCI_EMPRESA ( ID )
            ON DELETE CASCADE;

ALTER TABLE TCI_ITEM
    ADD CONSTRAINT TCI_ITEM_TCI_CARDAPIO_FK FOREIGN KEY ( TCI_CARDAPIO_ID )
        REFERENCES TCI_CARDAPIO ( ID )
            ON DELETE CASCADE;

ALTER TABLE TCI_CARDAPIO
    ADD CONSTRAINT TCI_CARDAPIO_TCI_EMPRESA_FK FOREIGN KEY ( TCI_EMPRESA_ID )
        REFERENCES TCI_EMPRESA ( ID )
            ON DELETE CASCADE;