CREATE SEQUENCE ATENDIMENTO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_ATENDIMENTO
    SET ID = ATENDIMENTO_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE ATENDIMENTO_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE CATEGORIA_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_CATEGORIA
    SET ID = CATEGORIA_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE CATEGORIA_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE EMPRESA_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_EMPRESA
    SET ID = EMPRESA_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE EMPRESA_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE ENDERECO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_ENDERECO
    SET ID = ENDERECO_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE ENDERECO_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE ITEM_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_ITEM
    SET ID = ITEM_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE ITEM_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE PLANO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_PLANO
    SET ID = PLANO_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE PLANO_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE CARDAPIO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_CARDAPIO
    SET ID = CARDAPIO_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE CARDAPIO_ID_SEQ;

-------------------------------------------

CREATE SEQUENCE RESPONSAVEL_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE TCI_RESPONSAVEL
    SET ID = RESPONSAVEL_ID_SEQ.NEXTVAL;
    
DROP SEQUENCE RESPONSAVEL_ID_SEQ;